# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\JetBrains\CLion 2019.3.2\bin\cmake\win\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\JetBrains\CLion 2019.3.2\bin\cmake\win\bin\cmake.exe" -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "C:\Users\i_maa\Documents\MASC\Class Metrics Library\ClassMetricsLib"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "C:\Users\i_maa\Documents\MASC\Class Metrics Library\ClassMetricsLib"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	"C:\Program Files\JetBrains\CLion 2019.3.2\bin\cmake\win\bin\cmake.exe" -E echo "No interactive CMake dialog available."
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\JetBrains\CLion 2019.3.2\bin\cmake\win\bin\cmake.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "C:\Users\i_maa\Documents\MASC\Class Metrics Library\ClassMetricsLib\CMakeFiles" "C:\Users\i_maa\Documents\MASC\Class Metrics Library\ClassMetricsLib\CMakeFiles\progress.marks"
	$(MAKE) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "C:\Users\i_maa\Documents\MASC\Class Metrics Library\ClassMetricsLib\CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/build
.PHONY : main/fast

#=============================================================================
# Target rules for targets named ClassMetrics

# Build rule for target.
ClassMetrics: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 ClassMetrics
.PHONY : ClassMetrics

# fast build rule for target.
ClassMetrics/fast:
	$(MAKE) -f CMakeFiles\ClassMetrics.dir\build.make CMakeFiles/ClassMetrics.dir/build
.PHONY : ClassMetrics/fast

Classification/BinaryClassification.obj: Classification/BinaryClassification.cpp.obj

.PHONY : Classification/BinaryClassification.obj

# target to build an object file
Classification/BinaryClassification.cpp.obj:
	$(MAKE) -f CMakeFiles\ClassMetrics.dir\build.make CMakeFiles/ClassMetrics.dir/Classification/BinaryClassification.cpp.obj
.PHONY : Classification/BinaryClassification.cpp.obj

Classification/BinaryClassification.i: Classification/BinaryClassification.cpp.i

.PHONY : Classification/BinaryClassification.i

# target to preprocess a source file
Classification/BinaryClassification.cpp.i:
	$(MAKE) -f CMakeFiles\ClassMetrics.dir\build.make CMakeFiles/ClassMetrics.dir/Classification/BinaryClassification.cpp.i
.PHONY : Classification/BinaryClassification.cpp.i

Classification/BinaryClassification.s: Classification/BinaryClassification.cpp.s

.PHONY : Classification/BinaryClassification.s

# target to generate assembly for a file
Classification/BinaryClassification.cpp.s:
	$(MAKE) -f CMakeFiles\ClassMetrics.dir\build.make CMakeFiles/ClassMetrics.dir/Classification/BinaryClassification.cpp.s
.PHONY : Classification/BinaryClassification.cpp.s

Classification/InputVectors/input.obj: Classification/InputVectors/input.cpp.obj

.PHONY : Classification/InputVectors/input.obj

# target to build an object file
Classification/InputVectors/input.cpp.obj:
	$(MAKE) -f CMakeFiles\ClassMetrics.dir\build.make CMakeFiles/ClassMetrics.dir/Classification/InputVectors/input.cpp.obj
.PHONY : Classification/InputVectors/input.cpp.obj

Classification/InputVectors/input.i: Classification/InputVectors/input.cpp.i

.PHONY : Classification/InputVectors/input.i

# target to preprocess a source file
Classification/InputVectors/input.cpp.i:
	$(MAKE) -f CMakeFiles\ClassMetrics.dir\build.make CMakeFiles/ClassMetrics.dir/Classification/InputVectors/input.cpp.i
.PHONY : Classification/InputVectors/input.cpp.i

Classification/InputVectors/input.s: Classification/InputVectors/input.cpp.s

.PHONY : Classification/InputVectors/input.s

# target to generate assembly for a file
Classification/InputVectors/input.cpp.s:
	$(MAKE) -f CMakeFiles\ClassMetrics.dir\build.make CMakeFiles/ClassMetrics.dir/Classification/InputVectors/input.cpp.s
.PHONY : Classification/InputVectors/input.cpp.s

Classification/MaryClassification.obj: Classification/MaryClassification.cpp.obj

.PHONY : Classification/MaryClassification.obj

# target to build an object file
Classification/MaryClassification.cpp.obj:
	$(MAKE) -f CMakeFiles\ClassMetrics.dir\build.make CMakeFiles/ClassMetrics.dir/Classification/MaryClassification.cpp.obj
.PHONY : Classification/MaryClassification.cpp.obj

Classification/MaryClassification.i: Classification/MaryClassification.cpp.i

.PHONY : Classification/MaryClassification.i

# target to preprocess a source file
Classification/MaryClassification.cpp.i:
	$(MAKE) -f CMakeFiles\ClassMetrics.dir\build.make CMakeFiles/ClassMetrics.dir/Classification/MaryClassification.cpp.i
.PHONY : Classification/MaryClassification.cpp.i

Classification/MaryClassification.s: Classification/MaryClassification.cpp.s

.PHONY : Classification/MaryClassification.s

# target to generate assembly for a file
Classification/MaryClassification.cpp.s:
	$(MAKE) -f CMakeFiles\ClassMetrics.dir\build.make CMakeFiles/ClassMetrics.dir/Classification/MaryClassification.cpp.s
.PHONY : Classification/MaryClassification.cpp.s

Classification/MultiLabelClassification.obj: Classification/MultiLabelClassification.cpp.obj

.PHONY : Classification/MultiLabelClassification.obj

# target to build an object file
Classification/MultiLabelClassification.cpp.obj:
	$(MAKE) -f CMakeFiles\ClassMetrics.dir\build.make CMakeFiles/ClassMetrics.dir/Classification/MultiLabelClassification.cpp.obj
.PHONY : Classification/MultiLabelClassification.cpp.obj

Classification/MultiLabelClassification.i: Classification/MultiLabelClassification.cpp.i

.PHONY : Classification/MultiLabelClassification.i

# target to preprocess a source file
Classification/MultiLabelClassification.cpp.i:
	$(MAKE) -f CMakeFiles\ClassMetrics.dir\build.make CMakeFiles/ClassMetrics.dir/Classification/MultiLabelClassification.cpp.i
.PHONY : Classification/MultiLabelClassification.cpp.i

Classification/MultiLabelClassification.s: Classification/MultiLabelClassification.cpp.s

.PHONY : Classification/MultiLabelClassification.s

# target to generate assembly for a file
Classification/MultiLabelClassification.cpp.s:
	$(MAKE) -f CMakeFiles\ClassMetrics.dir\build.make CMakeFiles/ClassMetrics.dir/Classification/MultiLabelClassification.cpp.s
.PHONY : Classification/MultiLabelClassification.cpp.s

main.obj: main.cpp.obj

.PHONY : main.obj

# target to build an object file
main.cpp.obj:
	$(MAKE) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/main.cpp.obj
.PHONY : main.cpp.obj

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... main
	@echo ... ClassMetrics
	@echo ... rebuild_cache
	@echo ... Classification/BinaryClassification.obj
	@echo ... Classification/BinaryClassification.i
	@echo ... Classification/BinaryClassification.s
	@echo ... Classification/InputVectors/input.obj
	@echo ... Classification/InputVectors/input.i
	@echo ... Classification/InputVectors/input.s
	@echo ... Classification/MaryClassification.obj
	@echo ... Classification/MaryClassification.i
	@echo ... Classification/MaryClassification.s
	@echo ... Classification/MultiLabelClassification.obj
	@echo ... Classification/MultiLabelClassification.i
	@echo ... Classification/MultiLabelClassification.s
	@echo ... main.obj
	@echo ... main.i
	@echo ... main.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

